[[pages]]
path = "pages/0 - Contexte.py"
name = "Pourquoi ?"
icon = "ğŸ¤”"

[[pages]]
path = "pages/1 - proposition_films.py"
name = "Films AlÃ©atoires"
icon = "ğŸ¥"

[[pages]]
path = "pages/2 - proposition_musique.py"
name = "Musique AlÃ©atoire"
icon = "ğŸ™ï¸"

[[pages]]
path = "pages/3 - proposition_livre.py"
name = "Livre AlÃ©atoire"
icon = "ğŸ“–"

[[pages]]
path = "pages/4 - maj_films.py"
name = "MAJ - Films"
icon = "ğŸ›ï¸"

[[pages]]
path = "pages/5 - maj_playlist.py"
name = "MAJ - Musique"
icon = "ğŸ›ï¸"

[[pages]]
path = "pages/6 - maj_livre.py"
name = "MAJ - Livres"
icon = "ğŸ›ï¸"