[[pages]]
path = "pages/0 - proposition_films.py"
name = "AlÃ©atoire"
icon = "ğŸ¥"

[[pages]]
path = "pages/1 - proposition_musique.py"
name = "AlÃ©atoire"
icon = "ğŸ™ï¸"

[[pages]]
path = "pages/2 - maj_films.py"
name = "Maj Liste Films"
icon = "ğŸ”"

[[pages]]
path = "pages/3 - maj_playlist.py"
name = "Maj Playlist"
icon = "ğŸ”"