[[pages]]
path = "pages/0 - Contexte.py"
name = "Contexte"
icon = "ğŸ¤”"

[[pages]]
path = "pages/1 - culturette russe.py"
name = "Culturette Russe"
icon = "ğŸ²"

[[pages]]
path = "pages/2 - proposition_films.py"
name = "Film"
icon = "ğŸ¥"

[[pages]]
path = "pages/3 - proposition_musique.py"
name = "Musique"
icon = "ğŸ™ï¸"

[[pages]]
path = "pages/4 - proposition_livre.py"
name = "Livre"
icon = "ğŸ“–"